"""add song and scale_positions to licks

Revision ID: ef642b4a92a3
Revises: 7352d04ce712
Create Date: 2026-08-29 19:13:42.361197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef642b4a92a3'
down_revision: Union[str, Sequence[str], None] = '7352d04ce712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('licks', sa.Column('song', sa.String(length=200), nullable=False))
    op.add_column('licks', sa.Column('scale_positions', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('licks', 'scale_positions')
    op.drop_column('licks', 'song')
    # ### end Alembic commands ###
