"""Module 2 (Scale Fluency) drill generator: position-crossing scale patterns.

Builds on app.engine.theory's scale/pitch math. The pattern is generated by
treating the scale as one continuous ascending run of pitches and slicing it
into equal groups per string — this is correct by construction (no heuristic
position-searching) since each note's fret falls directly out of MIDI
arithmetic. For the four 7-note scales this reproduces the standard 3-notes-
per-string (3nps) shape; for the two pentatonic scales, 2 notes per string
reproduces the standard pentatonic "box" shape (hand-verified: A minor
pentatonic starting at fret 5 comes out as the textbook 5-8/5-7/5-7/5-7/5-8/
5-8 box 1 shape). Notes-per-string is derived from the scale's note count,
not chosen by the caller, since it's a convention tied to the scale itself.
"""

from app.engine.theory import (
    MAX_FRET,
    MAX_STRING,
    MIN_STRING,
    SCALE_INTERVALS,
    SUPPORTED_KEYS,
    Drill,
    ascending_scale_tones,
    assign_tones_to_strings,
    fret_to_midi,
    scale_pitch_class_spelling,
)

# 7-note scales use 3 notes per string (3nps); 5-note pentatonic scales use 2.
NOTES_PER_STRING_BY_SCALE_SIZE = {7: 3, 5: 2}


def generate_scale_pattern(
    key: str = "C",
    scale: str = "major",
    start_string: int = 6,
    start_fret: int = 0,
    num_strings: int = 6,
) -> Drill:
    if key not in SUPPORTED_KEYS:
        raise ValueError(f"Unsupported key: {key!r}. Supported keys: {sorted(SUPPORTED_KEYS)}")
    if scale not in SCALE_INTERVALS:
        raise ValueError(f"Unsupported scale: {scale!r}. Supported scales: {sorted(SCALE_INTERVALS)}")

    lowest_string = start_string - num_strings + 1
    if not (MIN_STRING <= lowest_string <= start_string <= MAX_STRING):
        raise ValueError(
            f"start_string={start_string} with num_strings={num_strings} falls outside "
            f"{MIN_STRING}-{MAX_STRING}"
        )
    if not (0 <= start_fret <= MAX_FRET):
        raise ValueError(f"start_fret must be within 0-{MAX_FRET}, got {start_fret}")

    notes_per_string = NOTES_PER_STRING_BY_SCALE_SIZE[len(SCALE_INTERVALS[scale])]

    start_midi = fret_to_midi(start_string, start_fret)
    tones = ascending_scale_tones(key, scale, start_midi, num_strings * notes_per_string)
    spelling = scale_pitch_class_spelling(key, scale)
    strings = list(range(start_string, lowest_string - 1, -1))
    notes = assign_tones_to_strings(tones, strings, notes_per_string, spelling)

    scale_label = scale.replace("_", " ").title()
    return Drill(
        title=f"Scale Fluency — {key} {scale_label}, {notes_per_string}-Notes-Per-String",
        parameters={
            "key": key,
            "scale": scale,
            "start_string": start_string,
            "start_fret": start_fret,
            "num_strings": num_strings,
            "notes_per_string": notes_per_string,
        },
        notes=notes,
    )
